// object type
export type Entry = {
  id: React.Key;
  Created: string; // 1995-12-17T03:24:00
  Name: string;
  Email: string;
  Type: "aiscan2";
  RiscScore: "Not calculated" | "LOW";
  Status: "Approved" | "Rejected" | "Cancelled" | "Ready For Review" | "In Progress";
  StatusDescription?: string;
};
// "Customer Processing" | "User Accepted KYC invitation",
export async function getData(): Promise<Entry[]> {
  return [
    {
      id: 1,
      Created: "1995-12-17T03:24:00",
      Name: "John Doe",
      Type: "aiscan2",
      RiscScore: "Not calculated",
      Status: "Approved",
      Email: "assadad@asfsf.com",
    },
    {
      id: 2,
      Created: "1995-12-17T03:24:00",
      Name: "Jane Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "Customer Processing",
      Email: "assadad@asfsf.com",
    },
    {
      id: 3,
      Created: "1995-12-17T03:24:00",
      Name: "Jack Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },
    {
      id: 4,
      Created: "1995-12-17T03:24:00",
      Name: "Jill Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Approved",
      Email: "assadad@asfsf.com",
    },
    {
      id: 5,
      Created: "1995-12-17T03:24:00",
      Name: "James Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Approved",
      Email: "assadad@asfsf.com",
    },
    {
      id: 6,
      Created: "1995-12-17T03:24:00",
      Name: "Jessica Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Ready For Review",
      Email: "assadad@asfsf.com",
    },
    {
      id: 7,
      Created: "1995-12-17T03:24:00",
      Name: "Jacob Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Ready For Review",
      Email: "assadad@asfsf.com",
    },
    {
      id: 8,
      Created: "1995-12-17T03:24:00",
      Name: "Julia Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Rejected",
      Email: "assadad@asfsf.com",
    },
    {
      id: 9,
      Created: "1995-12-17T03:24:00",
      Name: "Justin Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },
    {
      id: 10,
      Created: "1995-12-17T03:24:00",
      Name: "Jennifer Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Cancelled",
      Email: "assadad@asfsf.com",
    },
    {
      id: 11,
      Created: "1995-12-17T03:24:00",
      Name: "Joshua Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },
    {
      id: 12,
      Created: "1995-12-17T03:24:00",
      Name: "Julian Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Approved",
      Email: "assadad@asfsf.com",
    },
    {
      id: 13,
      Created: "1995-12-17T03:24:00",
      Name: "Jasmine Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Approved",
      Email: "assadad@asfsf.com",
    },
    {
      id: 14,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 15,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 16,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 17,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 18,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 19,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 20,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 21,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 22,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 23,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 24,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 25,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 26,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 27,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 28,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 29,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 30,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 31,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 32,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 33,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 34,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 35,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 36,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 37,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 38,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 39,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 40,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 41,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "In Progress",
      StatusDescription: "User Accepted KYC invitation",
      Email: "assadad@asfsf.com",
    },

    {
      id: 42,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Rejected",
      Email: "assadad@asfsf.com",
    },

    {
      id: 43,
      Created: "1995-12-17T03:24:00",
      Name: "Jason Doe",
      Type: "aiscan2",
      RiscScore: "LOW",
      Status: "Rejected",
      Email: "assadad@asfsf.com",
    },

  ];
}
